### ISSUE TITLE
UC1 Check In - Populate Authorize person drop down list

### ISSUE THREAD

**Issue by linhub15** [linhub15/ECAC-Children-Ministry-Management#1]
### Input
* Household ID
### Output
* Authorized Person ID
* Authorized Person First Name
* Authorized Person Last Name

### TODO
- [x] Update Class Diagram & Data Dictionary
- [x] Add @IsAuthorized Parameter to Stored Procedure: InsertHouseHoldMember
- [x] BLL: Get Authorized People should get all people with "IsAuthorized == True"
- [x] DB: Add Test Data - 1 Person for each household ( IsAuthorized = True, IsMember = True)
- [x] UI: Display the list
### Test
- [x] Display All Authorized Persons for that houshold
