### ISSUE TITLE
UC1 - EventAttendee Modification

### ISSUE THREAD

**Issue by linhub15** [linhub15/ECAC-Children-Ministry-Management#11]
### TODO

- [x] DB: Modify EventAttendee Table to use composite primary key (EventID, PersonID, CheckInTime)
- [x] DB: Add Stored Procedure `CheckInEventAttendee(@PersonID, @EventID, @CheckInTime,@IsVolunteer,@CheckedInBy)`
   - WHERE CheckOutTime is not NULL (Do not let person check into event 2 times)
- [ ] DB: Modify Stored Procedure `CheckOutEventAttendee(@EventID, @PersonID, @CheckOutTime, @CheckedOutBy)`
   - Don't need checkIntime
   - WHERE CheckOutTime = Null (There will only be one of these)
- [x] DAL/BLL: Add EventID back to the procedures

**Comment by linhub15** [comment]
Complete!
