### ISSUE TITLE
UC2 Register - Implement Front End

### ISSUE THREAD

**Issue by tchu6** [linhub15/ECAC-Children-Ministry-Management#13]
Following the specs in Sequence Diagram, Class Diagram and UI Prototypes

### TODO
- [ ] Add database query to search for existing household by address 
- [ ] ^ Implement in Register Primary Adult View
- [ ] ^ Implement in Add to Existing Household View
- [ ] Implement Add Authorized Person
- [ ] ^ Search for existing person 
- [ ] Child Registration - Calculate child age in View
- [ ] Add UI in CheckIn to link to Register Person (when person searched is not found)
