### ISSUE TITLE
UC1 Check In - View Event Attendees ( List of all checked in people for that event )

### ISSUE THREAD

**Issue by linhub15** [linhub15/ECAC-Children-Ministry-Management#4]
Once people have been checked into the system, users will be able to see all the people checked in by selecting which event.

This list will allow people to be checked out 

### TODO
- [x] Create New Stored Procedure: GetEventAttendeesByEventID(EventID):List<Person>
- [x] Create BLL Methods: GetEventAttendees(EventID):List<Person>
- [x] Create UI to display View Event Attendees
- [x] Update Documentation
