### ISSUE TITLE
UC1 Check In - Check Out Event Attendees

### ISSUE THREAD

**Issue by linhub15** [linhub15/ECAC-Children-Ministry-Management#5]
### TODO
@tchu6 
- [x] BLL: Create Method `EventAttendeeManager.CheckOutPerson(PersonID, CheckOutTime, CheckedOutBy):Bool`
- [x] BLL: Create Method `CheckInManager.CheckOutPeople(List<EventAttendeeDTO>):Bool`
- [x] BLL: Create Method `RequestDirector.CheckOutPeople(List<EventAttendeeDTO>):Bool`

@linhub15
- [x] Model: Create EventAttendeeDTO
   ```
   + EventID : int
   + CheckedInTime : DateTime
   + CheckedOutTime : DateTime?

   + PersonID : int
   + FirstName : string
   + LastName : string

   + CheckedInByPersonID:int
   + CheckedInByPersonFirstName : string
   + CheckedInByPersonLastName : string
   + CheckedOutByPersonID : int
   ```
- [x] UI: Implement CheckInController.LoadEventAttendees(EventID)
- [x] BLL: Implement Method `CheckInController.GetEventAttendeeDTO(EventID):List<EventAttendeeDTO>`
   * Use as few database queries as possible, if no query exists, request Jevons to create one
- [x] BLL: Implement Method `RequestDirector.GetEventAttendeeDTO(EventID):List<EventAttendeeDTO>`
   * This is the method UI will call, it just calls the CheckInController method
- [x] UI: Display EventAttendees Partial view in index.cshtml
- [x] UI: Check Out Single/ Multiple people from the event. Include Authorized Person too.

@zhongyiguo 
- [ ] DB: Make / Update stored procedures based on what @tchu6 requires while he does the BLL
