### ISSUE TITLE
UC2 Register - Implement Database

### ISSUE THREAD

**Issue by linhub15** [linhub15/ECAC-Children-Ministry-Management#7]
Creating the data storage and stored procedures for Registering a person.

### TODO
- [x] Gather Requirements - Send Email to Clients
- [x] Analysis
- [x] Design DB 
- [x] Add 'Gender' attribute to Person table @zhongyiguo 
- [x] Documentation: Data Dictionary, Data Model, Class Diagram
- [ ] DB: Update Table Statements
- [ ] DB: Create Stored Procedures, Insert, Update
- [ ] BLL: Create Method RequestDirector.RegisterPerson(Person)
