### ISSUE TITLE
Add Alias to System

### ISSUE THREAD

**Issue by linhub15** [linhub15/ECAC-Children-Ministry-Management#8]
Client has mentioned that an Alias should also be included during registration to reduce the chance of duplication in the system if names are not found.
### TODO
- [x] Confirm Alias requirements
- [x] UC2 Register Person - Update Primary Scenario
- [ ] UC2 Register Person - Update UI
- [ ] UC2 Register Person - Update Sequence Diagram
- [x] UC2 Register Person - Update Class diagram
- [x] UC1 Check In - Update Data Model
- [x] UC1 Check In - Update Stored Procedure
