### ISSUE TITLE
UC2 Register - Implement Classes

### ISSUE THREAD

**Issue by linhub15** [linhub15/ECAC-Children-Ministry-Management#9]
Following the specs in Sequence Diagram and Class Diagram

### TODO
- [x] Implement RequestDirector Methods
- [x] Implement RegistrationManager Methods
- [x] Implement DatabaseManagers Methods
